### ISSUE TITLE
b-navbar-item doesn't respond to @click

### ISSUE THREAD

**Issue by hnnweb** [buefy/buefy#1818]
### Overview of the problem

**Buefy** version: 
─ buefy@0.8.4
│  └─ bulma@0.7.5
**Vuejs** version: vue@2.6.10
**OS/Browser**: Chrome 77.0.3865.90, MacOS 10.14.6

### Description

Event doesn't trigger when using 
```
<template>
<b-navbar>
	<template slot="start">
		<b-navbar-item @click="counter += 1">{{ counter }}</b-navbar-item>
	</template>
</b-navbar>
</template>
<script>
export default {
  name: "Example",
  data() {
    return {
			counter: 0
    }
  }
};
</script>
```

### Steps to reproduce
1. Click the "0" in the menu...

### Expected behavior

Raise by 1 per click

### Actual behavior
Still at 0

**Comment by jtommy** [comment]
Fixed https://github.com/buefy/buefy/issues/1784

**Comment by cperrin88** [comment]
I think this is still broken. I can't get the `@click` to work.

https://jsfiddle.net/806gadw2/

**Comment by jtommy** [comment]
Please use @click.native.
I'll add click event
