### ISSUE TITLE
Sidebar closes when click on dynamic content

### ISSUE THREAD

**Issue by petlun** [buefy/buefy#2998]
### Overview of the problem
Click on sidebars dynamic content closes the sidebar

**Buefy** version: [0.9.3]
**Vuejs** version: [2.6.12]
**OS/Browser**: Windows 10/Chrome 86.0.4240.111 

### Description
The sidebar closes when click on dynamic content.

### Steps to reproduce
https://codepen.io/petlun/pen/MWeJWzb
Click on "Show", then click the button "Show more" twice.
Click on item 10.

### Expected behavior
The sidebar remains open.

### Actual behavior
The sidebar closes.

**Comment by petlun** [comment]
I suspect it could be related to https://github.com/buefy/buefy/blob/dev/src/components/sidebar/Sidebar.vue#L126
The Document method querySelectorAll() returns a static (not live) NodeList

**Comment by jtommy** [comment]
Yes, i was checking it

**Comment by jtommy** [comment]
@petlun it has been fixed https://github.com/buefy/buefy/issues/2853. Available in the next release

**Comment by michaelcaterisano** [comment]
I'm still having this issue. https://codepen.io/michaelcaterisano/pen/YzGQVaZ

Steps to reproduce:
Click "open sidebar" button. Sidebar opens.
Click item in sidebar to remove from list. When item is the last item of the array, sidebar fires "close" event.

**Comment by highoncarbs** [comment]
@michaelcaterisano @jtommy  any update on this ? Same issue

**Comment by nikzanda** [comment]
+1, Same issue

**Comment by ldonis** [comment]
Same issue, it happens only when using v-if, workaround is use v-show instead (not really a solution)

**Comment by jtommy** [comment]
Just found a way, it's really tricky because it's relative to click listener queue but I added a way to check the element with the previous sidebar content 😄
